require("figarillo.plugins.lsp.mason")
require("figarillo.plugins.lsp.handlers").setup()
require("figarillo.plugins.lsp.null-ls")
require("figarillo.plugins.lsp.lspsaga")
require("figarillo.plugins.lsp.lenguages.tsserver")
